//! Hetzner Cloud + Hetzner DNS provider for Forge.
//!
//! Implements the cloud-agnostic [`forge_providers::CloudProvider`] trait fully against the
//! Hetzner Cloud API (`https://api.hetzner.cloud/v1`, `Authorization: Bearer`) and, optionally,
//! the Hetzner DNS API (`https://dns.hetzner.com/api/v1`, `Auth-API-Token` — a SEPARATE token).
//!
//! Notable behaviors handled here (see [`client`]):
//! - Asynchronous **action polling**: mutating calls return an `action`; we poll
//!   `GET /actions/{id}` until `success`/`error`.
//! - **Pagination** over `page`/`per_page=50`, following `meta.pagination.next_page`.
//! - **Rate-limit awareness**: HTTP 429 and exhausted `RateLimit-Remaining` map to
//!   [`forge_providers::ProviderError::RateLimited`].
//! - **Partial-failure cleanup**: a failed multi-step provision tears down resources created
//!   during the attempt and returns [`forge_providers::ProviderError::PartialFailure`].
//!
//! Credentials are never logged.

#![forbid(unsafe_code)]

mod client;
mod provider;

pub use client::{HETZNER_CLOUD_API, HETZNER_DNS_API, HetznerClient};
pub use provider::HetznerProvider;

use serde::{Deserialize, Serialize};

/// Construction-time configuration for a Hetzner provider.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HetznerConfig {
    /// Hetzner Cloud API token (Bearer). Required.
    pub api_token: String,
    /// Hetzner DNS API token (`Auth-API-Token`). Optional; enables DNS operations.
    pub dns_token: Option<String>,
}

impl HetznerProvider {
    /// Build a provider from a [`HetznerConfig`] against the real Hetzner endpoints.
    #[must_use]
    pub fn from_config(config: HetznerConfig) -> Self {
        Self::new(HetznerClient::new(config.api_token, config.dns_token))
    }
}

/// Generate a hardened cloud-init script for Forge agent bootstrap.
///
/// Security posture:
/// - Package updates + unattended security upgrades.
/// - SSH password auth disabled, root login disabled.
/// - Default-deny UFW firewall opening only SSH + the agent's control-plane ports.
/// - Locked-down permissions on the agent config directory.
///
/// `enrollment_token` is embedded in the user-data; treat the resulting script as a secret.
#[must_use]
pub fn build_agent_cloud_init(
    control_plane_url: &str,
    enrollment_token: &str,
    desired_hostname: Option<&str>,
) -> String {
    let hostname = desired_hostname.unwrap_or("forge-node");
    let cp = control_plane_url.trim_end_matches('/');
    let token = enrollment_token;

    format!(
        r#"#cloud-config
# Forge Agent - Hardened Hetzner Bootstrap (generated by forge-provider-hetzner)
hostname: {hostname}
package_update: true
package_upgrade: true

# Security hardening
ssh_pwauth: false
disable_root: true

users:
  - name: forge
    groups: docker
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true

# Basic firewall + fail2ban
runcmd:
  - |
    apt-get install -y ufw fail2ban unattended-upgrades
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow 22/tcp
    # Agent control plane ports (adjust if you use custom ports)
    ufw allow 8080/tcp
    ufw allow 6001/tcp
    ufw --force enable
  - |
    curl -fsSL {cp}/install-agent.sh | bash -s -- \
      --control-plane="{cp}" \
      --enrollment-token="{token}"
  - |
    chown -R root:root /etc/forge
    chmod 700 /etc/forge
    systemctl restart forge-agent || true

# Enable automatic security updates
unattended-upgrades:
  origins:
    - ${{distro_id}}:${{distro_codename}}
    - ${{distro_id}}:${{distro_codename}}-security
  auto-fix: true
"#
    )
}

#[cfg(test)]
mod cloud_init_tests {
    use super::*;

    #[test]
    fn cloud_init_embeds_control_plane_and_token() {
        let out = build_agent_cloud_init("https://cp.example.com/", "tok_abc", Some("node-1"));
        assert!(out.contains("hostname: node-1"));
        assert!(out.contains("--control-plane=\"https://cp.example.com\""));
        assert!(out.contains("--enrollment-token=\"tok_abc\""));
        assert!(out.contains("ssh_pwauth: false"));
    }
}
